### ISSUE TITLE
Cannot load the test api-tutorial application.

### ISSUE THREAD

**Issue by dnear** [spotify/apps-tutorial#40]
I have seen some other people having issues with loading their api-tutorial application inside the spotify client. I tried to load the api-tutorial both on my Windows and Linux computer but both did not succeed. I am wondering, because I have seen alot of people saying if you register a developer account you will get a menu item called 'Develop'. But I cannot see this, even when I reinstalled my Spotify.

I have created the Spotify folder inside C:/Users/David/My Documents/ and also (because I run a dutch version of windows) C:/Users/David/Documenten (this is also automatically translated by windows? because I also see this when Right-click as C:/Users/David/Documents/). 

I also placed the newest version of the api-tutorial in there. 

Nothing works, I tried for 2 days now.

**Comment by thelinmichael** [comment]
Hi @dnear!

It's great to hear that you want to build using our platform. First of all, as you've already figured out, the key to solving your problem is to register you as a Developer so that you can load local applications in your Spotify client. This can be sorted manually if necessary. However, I can't recommend enough that you spend your energy on using the [Web API](https://developer.spotify.com/web-api/) or the mobile SDKs ([Android](https://developer.spotify.com/technologies/spotify-android-sdk/), [iOS](https://developer.spotify.com/technologies/spotify-ios-sdk/)). The closure of the Apps platform was announced in March 2014 and no new App submissions have been added to the client since. Read more about the move from Apps to Web API [here](https://developer.spotify.com/news-stories/2014/03/24/closure-of-spotify-apps-submissions/). Please do let me know if you still need help registering yourself as a developer.

**Comment by dnear** [comment]
Thanks for your answer. Although its quite clear for me now, I stil have one question. I wanted to create an application for users to use (so not for local use). Although for this application I do need information about song the user is listening at the moment. Will I still be able with the usage of the modern Web API to retrieve this kind of information? 

I have the idea that the new Web API is completely seperate from the curently still existing apps like MusiXmatch and etc. And I have also have the idea that only those apps like MusiXmatch and etc are able to do this.

**Comment by thelinmichael** [comment]
@dnear, unfortunately information about which track a user is listening to is not currently available using the Web API.

**Comment by dnear** [comment]
Ah that's unfortunate. Well thank you for your kindness.
